version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  celery-worker:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - server
      - redis

  celery-beat:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - server
      - redis

  redis:
    image: redis:7.0.5-alpine
    env_file:
      - .env